import Head from 'next/head';
import dynamic from 'next/dynamic';

const Map = dynamic(() => import('../components/Map'), { ssr: false });

const Home: React.FC = () => (
  <>
    <Head>
      <title>Snapp Map</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <main className='main'>
      <Map />
    </main>
  </>
);

export default Home;
